### ISSUE TITLE
Improvement in UI : Add Navbar

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Snake_Game#12]
Add basic (black/gray background) navbar with following nav links :
1. Brand (Normal styled bold text will work. Keep the name as SnakyJS)
2. About (Currently it'll not be linked with any page)
3. New Game (Clicking this will reload the page i.e it will reset to original score and length)

Note : 
All Changes must be made in index.html
Styles should be added in the relevant stylesheets only (avoid inline styles)

**Comment by jad837** [comment]
Hi I will like to work on this.

**Comment by Vishal1003** [comment]
Sure!
