### ISSUE TITLE
Improve UI : Style the fruit and score block

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Snake_Game#13]
Give proper styling to the fruit ( may be red colored fruit will look good! ). 
Also add the score label and give it a unique style.

Note : 
All changes must be made in index.html
Styles must be added in the relevant stylesheet. (avoid inline styles )

**Comment by haseeb1009** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by Vishal1003** [comment]
sure

**Comment by haseeb1009** [comment]
@Vishal1003  As per this issue, I am improving the fruit and score block styles but I would suggest the overall scaling and canvas improvement too, which can be done by adding some more issues.

**Comment by Vishal1003** [comment]
@haseeb1009 thank you for your suggestion. I'll surely add more issues for improvement in UI
