### ISSUE TITLE
Make the division of the game small.

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Snake_Game#5]
Decrease the size of the game box and align the score on the top.

**Comment by Nopraz** [comment]
hi ! i will work on that

**Comment by Nopraz** [comment]
I created a pull request for this : #7

**Comment by Vishal1003** [comment]
@Nopraz Thank you for your efforts. I've merged your pr.

**Comment by lewis150193** [comment]
Is this still open for contribution?
